name: CI
on: [ push, pull_request ]
env:
  CI: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  DEPLOY_NODE_VERSION: 25.x
permissions:
  contents: read
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x, 24.x, 25.x ]
    steps:
      - name: git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: yarn cache
        uses: actions/cache@v5
        with:
          path: ~/.yarn/berry/cache
          key: ${{runner.os}}-node${{matrix.node-version}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.os}}-node${{matrix.node-version}}-yarn-
      - name: Set up Node.js v${{matrix.node-version}}
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}
      - run: corepack yarn
      - run: corepack yarn test
      - run: corepack yarn lint
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: yarn cache
        uses: actions/cache@v5
        with:
          path: ~/.yarn/berry/cache
          key: ${{runner.os}}-node${{matrix.node-version}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.os}}-node${{matrix.node-version}}-yarn-
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{env.DEPLOY_NODE_VERSION}}
      - run: |
          npm install -g \
            @semantic-release/commit-analyzer@13.0.1 \
            @semantic-release/release-notes-generator@14.1.0 \
            @semantic-release/npm@13.1.5 \
            @semantic-release/github@12.0.6 \
            @softwareventures/semantic-release-config@9.0.0 \
            conventional-changelog-conventionalcommits@9.3.0 \
            semantic-release@25.0.3 \
            semantic-release-pinst@1.1.0
      - run: corepack yarn
      - run: semantic-release
